### PR TITLE
Fixed multiple build issues

### LINKED ISSUE #517: Unable to build on certain Windows Machines
The default build.cmd file does not specify a default Platform thus the platform is set the path specific platform of the Windows Machine which is not always a valid platform for the build process.

### PR DESCRIPTION
**Pull request by husterk**
Fixes #517 and #519.

### CODE REVIEW

**Comment by husterk** [comment]
Finally straightened out the pull requests. Thanks for being patient with me. I am still learning my way around GitHub.

**Comment by carolynvs** [comment]
No worries, I really do appreciate the help! I will review later today.

**Comment by carolynvs** [comment]
@husterk If you don't mind, I would like to better understand why you wanted to build via build.cmd all those different configurations e.g. build debug (the current default), build release, build debug + package, etc. 

I had originally intended build.cmd to help people who are new to the project do the most simple thing: clone and run build.cmd to get started, avoiding the slow documentation part. I had assumed that in more advanced cases one would use msbuild directly but it looks like that in order for someone to contribute, that isn't really enough. :smile: I'm hoping you can help give me a bit more context so that I can do better in the future.

1. Why did you want to make build.cmd a complete wrapper for the msbuild project instead of calling msbuild for more advanced scenarios? e.g. `msbuild build\build.proj /t:Package`
2. Why did you need to build in release mode? Was that something you had to test separately when developing your fix or was it simply included for completeness sake?
3. Why did you need to build the NuGet package? Were you using that nupkg to test out your changes or were you copying the dll from the bin?

**Comment by husterk** [comment]
@carolynvs 

1. Why did you want to make build.cmd a complete wrapper for the msbuild project instead of calling msbuild for more advanced scenarios? e.g. msbuild build\build.proj /t:Package
*In my opInion, i is easier for a new user to leverage a pre-configured build.cmd file then trying to manually figure out which msbuild options / features to use. The build.cmd options should also be documented on the GitHub page.*

2. Why did you need to build in release mode? Was that something you had to test separately when developing your fix or was it simply included for completeness sake?
*This was mainly added for completeness sake and to allow a developer to execute a final "production" test prior to issuing a pull request.*

3. Why did you need to build the NuGet package? Were you using that nupkg to test out your changes or were you copying the dll from the bin?
*I needed to integrate this fix ASAP and we use NuGet for all of our third party references (where available). It was just easier for me to integrate a local NuGet package vs manually copying in and referencing the assemblies.*

**Comment by carolynvs** [comment]
@husterk Thanks for the details!

What was the error or problem you had when building without the /platform flags? I'm hoping I can clean up the solution configurations so that we don't have to explicitly set the platform twice (once in the solution and again in this build file). I'd like to be able to reproduce the problem so that I can test out the changes.

**Comment by carolynvs** [comment]
We could simplify the targets if we had build.cmd pass in Configuration as an argument, e.g. `build.cmd /configuration Release` would turn around and execute `msbuild build.proj /p:Configuration=Release`.

Also since the msbuild targets all use DependsOnTargets, I think we could have people just specify the desired final target, and not have to specify all the targets that lead up to it. So for example ExecuteBuildAndPackage could simply be Package.  Publish should be removed because no one can publish to nuget.org anyway.

I think we could distill the build.cmd arguments down to this:

```bash
# Execute default target (build) in Debug mode
build.cmd

# Execute default target (build) in Release mode
build.cmd /Configuration Release

# Execute Package target in Release mode
build.cmd Package /Configuration Release
```

You have definitely laid the groundwork for this; this will be much easier to use. What do you think? I'm happy to take your ideas and run with it if you are busy, or you can update the PR with these changes. Just let me know.

Thanks again for the great discussion and ideas! :smiley:

**Comment by husterk** [comment]
@carolynvs I like the approach you laid out. Feel free to run with it. I will be very busy for the next few days and I don't think that I would be able to update the PR till sometime next week.

**Comment by carolynvs** [comment]
@husterk Will do! Thanks again for the great suggestions. Enjoy your weekend!

**Comment by carolynvs** [comment]
I've implemented the goals from this PR in commit 33ccc42e6638395011c43bb7d8069ff3efe160e3 and am closing.

**Pull request closed without merging**
