### PR TITLE
Initial support for OpenStack Identity V3

### LINKED ISSUE #503: Support Identity v3
Hi!

Since the release of Openstack Havana the preferred version of Identity to use is v3. Some cloud providers have now migrated to only supporting v3 for token generation to get support for domains.

Currently the Openstack.NET SDK does not work with providers that require support for Identity v3.

Would it be possible to add support for Identity v3 in this project as well?

### PR DESCRIPTION
**Pull request by sharwell**
# Work In Progress

--

Fixes #503

### CODE REVIEW

**Comment by carolynvs** [comment]
The target branch is invalid now #510 has split v1 and v2 into separate branches.

**Comment by halcyondude** [comment]
Was this work folded into master, or is it still pending / active work?  I have a body of code based on an older, pre-"split" version of this project, and I'm wondering what the correct approach is to adding keystone v3 support.  I'm happy to contribute, but unclear how to start :)  Is this basically "stalled" work, prior to the refactoring of the project?

**Comment by sharwell** [comment]
@halcyondude The "2.0.0" library which this pull request updated was removed from the main code base in #510 with a new branch **v2** created that still contained the code. At some later point, the **v2** branch was deleted, which suggests there is no plan to incorporate *this* Identity v3 implementation in the SDK. Since #503 is still open, I wouldn't be surprised to see an alternate implementation proposed in a new pull request (I haven't asked if anyone is currently working on this).

The [**v2-identity-v3**](https://github.com/sharwell/openstack.net/compare/v2-identity-v3) branch remains available in my fork of the SDK. If someone wanted to work on completing the functionality in this pull request I would be open to discussing the remaining work within my fork. The starting point would be the `NotImplementedException` instances you see in this pull request, but there is quite a bit of documentation and testing missing as well.

**Comment by carolynvs** [comment]
@halcyondude Correct. The work from this pull request was intended for the rewrite of OpenStack.NET, and since I decided to not move forward with that, I closed this PR...

The current game plan is [splitting out Rackspace and other provider specific code from OpenStack.NET](https://github.com/openstacknetsdk/openstack.net/wiki/Rackspace-and-OpenStack.NET). I'm doing compute as we speak and next is identity, both v2 and [implementing v3](https://github.com/openstacknetsdk/openstack.net/issues/503).

Since identity v3 doesn't exist already, there's no reason why we couldn't start on that now, if you would like to help? :smiley:  Let me know if you are interested. I can jump start a branch with the necessary class definitions (e.g. `OpenStack.Identity.v3.IdentityService`) for us to work on together.

**Pull request closed without merging**
