### PR TITLE
WIP Migrate to paket for dependency management

### PR DESCRIPTION
**Pull request by smoothdeveloper**
This is my initial first spike at migrating.

I figured that the version conflicts I was mentioning in #616 were legit (due to building documentation for previous versions of openstack.net)

I'm not able to run integration tests, nor to build the documentation.

I think we need a nuget source for the special version of SFHB that is used and probably some other adjustments.

### CODE REVIEW

**Comment by carolynvs** [comment]
Yeah I inherited the project with a special build of SHFB... I can get that merged/building and then run the integration tests. Probably won't get to it until tomorrow though.

Thanks!

**Comment by smoothdeveloper** [comment]
I just added you as a contributor so you can push to the fork directly.

Also added missed important paket.lock and the setting to get binding redirects generated.

For SHFB, the simplest might be to put that in a folder in the repository that we can add as a nuget source if you can't get the changes upstream, upgrading SHFB can involve some more work with all settings to build the help, I'm not super familiar with it.

**Comment by carolynvs** [comment]
How are you building the doc? At one point I had hamemered out anyone building it without installing, but maybe that's broken over time.

https://github.com/openstacknetsdk/openstack.net/blob/develop/src/Documentation/README.md

**Comment by smoothdeveloper** [comment]
Yes using that one, and I looked at build.proj a bit.

**Comment by carolynvs** [comment]
Doh! I'll make sure to get that working again too.

**Comment by carolynvs** [comment]
@smoothdeveloper Sorry this took me so long! You were 99% of the way there and a few tweaks got everything building and tests passing. I've just manually merged into develop.

I was not planning on a separate release for this, as this is the first step in fixing things on the build side and doesn't modify the final nuget package. If that isn't right:, please let me know!

**Pull request closed without merging**
